[package]
name = "emuZCS"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "2.33", features = ["yaml"] }
colored = "2"
termios = "0.3.3"
termion = "1.5.6"